const wilayasList = [
  {
    id: 1,
    name: "Adrar",
    shippingPriceOffice: 800,
    shippingPriceHome: 1400,
  },
  {
    id: 2,
    name: "Chlef",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 3,
    name: "Laghouat",
    shippingPriceOffice: 600,
    shippingPriceHome: 1050,
  },
  {
    id: 4,
    name: "Oum El Bouaghi",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 5,
    name: "Batna",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 6,
    name: "Bejaia",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 7,
    name: "Biskra",
    shippingPriceOffice: 600,
    shippingPriceHome: 1050,
  },
  {
    id: 8,
    name: "Bechar",
    shippingPriceOffice: 800,
    shippingPriceHome: 1400,
  },
  {
    id: 9,
    name: "Blida",
    shippingPriceOffice: 350,
    shippingPriceHome: 750,
  },
  {
    id: 10,
    name: "Bouira",
    shippingPriceOffice: 350,
    shippingPriceHome: 750,
  },
  {
    id: 11,
    name: "Tamanrasset",
    shippingPriceOffice: 1200,
    shippingPriceHome: 1600,
  },
  {
    id: 12,
    name: "Tebessa",
    shippingPriceOffice: 600,
    shippingPriceHome: 1050,
  },
  {
    id: 13,
    name: "Tlemcen",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 14,
    name: "Tiaret",
    shippingPriceOffice: 350,
    shippingPriceHome: 750,
  },
  {
    id: 15,
    name: "Tizi Ouzou",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 16,
    name: "Alger",
    shippingPriceOffice: 350,
    shippingPriceHome: 750,
  },
  {
    id: 17,
    name: "Djelfa",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 18,
    name: "Jijel",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 19,
    name: "Setif",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 20,
    name: "Saida",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 21,
    name: "Skikda",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 22,
    name: "Sidi Bel Abbes",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 23,
    name: "Annaba",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 24,
    name: "Guelma",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 25,
    name: "Constantine",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 26,
    name: "Medea",
    shippingPriceOffice: 300,
    shippingPriceHome: 500,
  },
  {
    id: 27,
    name: "Mostaganem",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 28,
    name: "M'sila",
    shippingPriceOffice: 350,
    shippingPriceHome: 750,
  },
  {
    id: 29,
    name: "Mascara",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 30,
    name: "Ouargla",
    shippingPriceOffice: 600,
    shippingPriceHome: 1050,
  },
  {
    id: 31,
    name: "Oran",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 32,
    name: "El Bayadh",
    shippingPriceOffice: 800,
    shippingPriceHome: 1040,
  },
  {
    id: 33,
    name: "Illizi",
    shippingPriceOffice: 1200,
    shippingPriceHome: 1600,
  },
  {
    id: 34,
    name: "Bordj Bou Arreridj",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 35,
    name: "Boumerdes",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 36,
    name: "El Tarf",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 37,
    name: "Tindouf",
    shippingPriceOffice: 1200,
    shippingPriceHome: 1600,
  },
  {
    id: 38,
    name: "Tissemsilt",
    shippingPriceOffice: 350,
    shippingPriceHome: 750,
  },
  {
    id: 39,
    name: "El Oued",
    shippingPriceOffice: 600,
    shippingPriceHome: 1050,
  },
  {
    id: 40,
    name: "Khenchela",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 41,
    name: "Souk Ahres",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 42,
    name: "Tipaza",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 43,
    name: "Mila",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 44,
    name: "Ain Defla",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 45,
    name: "Naama",
    shippingPriceOffice: 800,
    shippingPriceHome: 1400,
  },
  {
    id: 46,
    name: "Ain Temouchent",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
  {
    id: 47,
    name: "Ghardaia",
    shippingPriceOffice: 600,
    shippingPriceHome: 1050,
  },
  {
    id: 48,
    name: "Relizane",
    shippingPriceOffice: 400,
    shippingPriceHome: 900,
  },
];

export default wilayasList;
